#==============================================================================#
#  Author:       Dominik Müller                                                #
#  Copyright:    2024 IT-Infrastructure for Translational Medical Research,    #
#                University of Augsburg                                        #
#                                                                              #
#  This program is free software: you can redistribute it and/or modify        #
#  it under the terms of the GNU General Public License as published by        #
#  the Free Software Foundation, either version 3 of the License, or           #
#  (at your option) any later version.                                         #
#                                                                              #
#  This program is distributed in the hope that it will be useful,             #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of              #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
#  GNU General Public License for more details.                                #
#                                                                              #
#  You should have received a copy of the GNU General Public License           #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#==============================================================================#
#-----------------------------------------------------#
#                  Site Information                   #
#-----------------------------------------------------#
site_name: AUCMEDI
site_description: a framework for Automated Classification of Medical Images
site_author: University Augsburg
site_url: https://frankkramer-lab.github.io/aucmedi/
copyright: Copyright &copy; 2021 - 2023 University of Augsburg

#-----------------------------------------------------#
#                       Layout                        #
#-----------------------------------------------------#
theme:
  name: "material"
  custom_dir: docs/theme_override/
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  palette:
    primary: indigo
  icon:
    logo: material/heart-pulse
    repo: fontawesome/brands/github

repo_url: https://github.com/frankkramer-lab/aucmedi
repo_name: frankkramer-lab/aucmedi

extra_css:
- css/mkdocstrings.css
- css/progressbar.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/frankkramer-lab/aucmedi
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/aucmedi/
    - icon: fontawesome/brands/docker
      link: https://github.com/frankkramer-lab/aucmedi/pkgs/container/aucmedi
    - icon: fontawesome/solid/book
      link: https://zenodo.org/record/6633540

#-----------------------------------------------------#
#                       Content                       #
#-----------------------------------------------------#
nav:
- Home: index.md
- Workflow: workflow.md
- Getting Started:
    - Introduction: getstarted/intro.md
    - Current Status: getstarted/status.md
    - Installation: getstarted/setup.md
    - Modules:      getstarted/modules.md
    - Quick Start - Framework:  getstarted/usage_api.md
    - Quick Start - AutoML:  getstarted/usage_automl.md
    - Contributing: getstarted/contribution.md
    - How to cite: getstarted/cite.md
- Examples:
  - Framework: examples/framework.md
  - AutoML: examples/automl.md
  - Tutorials: examples/tutorials.md
  - Applications: examples/applications.md
- AutoML:
  - Overview: automl/overview.md
  - Dataset Structure: automl/dataset.md
  - Parameters: automl/parameters.md
  - Command Line Interface:
    - Introduction: automl/cli/intro.md
    - Usage: automl/cli/usage.md
  - Docker:
    - Introduction: automl/docker/intro.md
    - Usage: automl/docker/usage.md
- API Reference: reference/
- About Us: about.md

#-----------------------------------------------------#
#                 Plugins & Extensions                #
#-----------------------------------------------------#
markdown_extensions:
- admonition
- def_list
- tables
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.progressbar
- pymdownx.tasklist
- pymdownx.superfences
- pymdownx.details
- pymdownx.arithmatex
- pymdownx.snippets
- toc:
    permalink: "¤"

plugins:
- search
- gen-files:
    scripts:
      - docs/auto_docstring.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    default_handler: python
    watch:
      - aucmedi
    handlers:
      python:
        selection:
          docstring_style: google
        rendering:
          show_root_heading: True
          show_submodules: False
          merge_init_into_class: True
          separate_signature: True
          members_order: source
          docstring_section_style: spacy
